### ISSUE TITLE
Remove `Lucy`?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#102]
It had a great promise, but the movie itself was IMHO terrible. Only good part was Morgan Freeman explaining stuff. Thoughts?

https://github.com/sindresorhus/awesome-scifi#lucy-2014-64

I'm not alone in this:
https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crroh51

**Comment by elssar** [comment]
I haven't seen the movie so can't say anything about that, but isn't a great premise enough to get on the list? It might not be great, but if the premise is good enough to spark someones imagination or provide fodder for day dreams about science and technology, then I think it's worth consuming.

**Comment by aleksandar-todorovic** [comment]
Well, I might be a bit biased since I was the one who added that movie, but I don't really think that we should on removing the movies. Instead of that, we should focus on actually adding the movies to that section. After all, we did receive some complains about the movies section being poor at the moment.

After the movie section gets enough titles, it would be easy to remove the movies that we don't think satisfies the criteria.

**Comment by cassidoo** [comment]
Hmmm I personally really *really* disliked this movie, so I'm down to remove it.  Like it didn't inspire as much as it...angered. :smile: 
I'd rather have a small set of quality, awesome things rather than a large database of things that people *might* like.

**Comment by icyflame** [comment]
Well, I have seen the movie, and it was _okay_. I think it makes the cut to make it into the list. It has a great premise, and the plot revolves around that premise, instead of digressing. It does get pretty boring, pretty fast. But I think we shouldn't remove the movie!

**Comment by RichardLitt** [comment]
I'd say remove it because if it's not awesome, it shouldn't be here.

**Comment by elssar** [comment]
@RichardLitt good point.

**Comment by RichardLitt** [comment]
Executive decision. @aleksandar-todorovic Thanks for adding it. :) All part of the process. This issue can be reopened if someone feels strongly that this movie is, indeed, awesome.

**Comment by aleksandar-todorovic** [comment]
It's OK, if most of the other contributors agree with the decision (like in this particular case), than that's the way it should be. No hard feelings. :)
