### ISSUE TITLE
Remove `Prometheus`?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#103]
It was just so bad. Good CG, but absolutely no story or character.

https://github.com/sindresorhus/awesome-scifi#prometheus-2012-70

**Comment by elssar** [comment]
I didn't like the movie either. There were just too many plot holes, and flaws all around. I wouldn't recommend this movie

**Comment by mihailim** [comment]
I won't weep if it's gone... couldn't even finish watching the BluRay (got annoyed about 2/3rds in), so it's most *definitely* not on my awesome list.

**Comment by tjFogarty** [comment]
I want to like it, if just for the place it tries to occupy in the Alien universe. That doesn't seem like a good reason though, so yeah... bury it. :disappointed:
