### ISSUE TITLE
Add `Equilibrium`?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#104]
http://www.imdb.com/title/tt0238380/

https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crroh51

**Comment by elssar** [comment]
The premise is a bit interesting, but the gun kata stuff was off putting. Futuristic dystopian society where human emotion is regulated in some way, has been done quiet a lot of times, and I doubt this movie would make a recommended list of just that, so don't see the point of having it in this list.

I wouldn't recommend it.

**Comment by mihailim** [comment]
I agree. The execution was entertaining, but the movie as such was very, *very* derivative. Not much innovative in it, and I would definitely not classify it as awesome.
