### ISSUE TITLE
Add `Edge of Tomorrow`?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#105]
Thrilling and original. Feels like a cross between Halo (the game), Groundhog Day and The Butterfly Effect.

http://www.imdb.com/title/tt1631867/

**Comment by elssar** [comment]
It was pretty good, the premise is quiet interesting, and the acting was quiet good. The manga was nice as well, though very different from the movie, too short and a bit confusing.

**Comment by tjFogarty** [comment]
For sure. I thought it was great, and I was a bit anxious about there being so many scenes repeating the same thing, but it worked!

**Comment by aleksandar-todorovic** [comment]
Watched it last night. I have to say that Chappie and this movie were the most interesting movies I watched since the beginning of the year.
