### ISSUE TITLE
It's kind of weird for Permutation City and Schild's Ladder to be under "Soft Science Fiction".

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#107]
Where should they be?

https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crrj345

**Comment by mihailim** [comment]
They're right. _Schild's Ladder_ is SF so hard you could cut diamond with it, and _Permutation City_, while definitely softer, is also definitely hard SF :)

**Comment by web3d0** [comment]
Just had to go "pppfffttttt!" in amused horror at the idea of those books being "soft". I don't think there is any book ever written that is harder SF than Schild's Ladder, or any triology that is harder SF than these three (including Diaspora). If there's a top 10 of all time hard SF ever written, Schild's Ladder is #1.
