### ISSUE TITLE
Add `Altered Carbon`?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#109]
https://www.goodreads.com/book/show/40445.Altered_Carbon

Suggested in https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crs0m3q

**Comment by elssar** [comment]
Definitely seems interesting.

**Comment by helderroem** [comment]
+1

**Comment by marcoslhc** [comment]
OMG that series is excellent! +1… K

**Comment by RichardLitt** [comment]
@marcoslhc @helderroem want to add reviews?

**Comment by mihailim** [comment]
Added :)
