### ISSUE TITLE
Add the Expanse series by James S. A. Corey?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#110]
https://www.goodreads.com/book/show/8855321-leviathan-wakes

Suggested in https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crs0m3q and https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crrwfjj

**Comment by elssar** [comment]
It's on my amazon wishlist(which I basically maintain as a to-read list). I haven't read it(and probably won't for a long time, as I have about 50 unread books lying around), but is something I would like to read.

**Comment by jpkempf** [comment]
I just started reading the fifth one and yes, the whole series definitely deserves a place on the list. I might do a pull request later if I get a chance, but for now it at least has my vote.

**Comment by RichardLitt** [comment]
@jpkempf Did you finish it?

**Comment by jpkempf** [comment]
@RichardLitt I did and I liked it quite a bit. Great writing as usual.

Still no news on that pull request though... I'm a bit intimidated by all those subcategories we have now, to be honest. I'm neither quite sure what all of them mean nor where I would place the Expanse series. Maybe I'll just write something up and put it under general Science Fiction and you can see if should go someplace else?

**Comment by RichardLitt** [comment]
Hmm, very good point; the subcats are confusing. I'll see about adding a note to make it less so. Yes, just throw it into general Science Fiction. :+1:
