### ISSUE TITLE
Miscategorization?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#111]
https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crriifl

> 'Soft Sci Fi' list which includes Schild's Ladder.... that's some pretty hard scifi right there.
permalinksavereportgive goldreplybuffer
[–]CalvinR 3 points 6 days ago 
Also Flower's for Algrenon would probably not be classified as Bio Punk but as Soft Sci Fi
permalinksaveparentreportgive goldreplybuffer
[–]St4rburn 2 points 7 days ago 
I have a feeling they got soft and hard missed up, considering the martian is not in hard.
permalinksaveparentreportgive goldreplybuffer
[–]elegance_shortfall 1 point 5 days ago 
And Greg Egan's awesome Orthogonal series isn't listed, which is basically a lesson in why you should pay attention in physics and maths classes.

**Comment by RichardLitt** [comment]
Flowers for Algernon is biological science fiction. It's not exactly biopunk. I don't know why biopunk is even a category, really.

**Comment by RichardLitt** [comment]
I haven't read Schild's Ladder, The Martian, or Orthogonal. What do we do to categorize these properly, in this case? Go home and read them?

**Comment by mihailim** [comment]
All three are hard SF. The Martian is more relaxed; Schild's Ladder and Orthogonal are so hard it actually helps to have taken an introductory course to quantum electrodynamics :)

**Comment by RichardLitt** [comment]
Moved the Martian, added #127. Thanks @mihailim.
