### ISSUE TITLE
Add `The Metamorphosis of Prime Intellect`?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#112]
https://www.goodreads.com/book/show/64341.The_Metamorphosis_of_Prime_Intellect

Suggested in https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crrmiw9

**Comment by elssar** [comment]
Read the Goodreads description and straightaway googled it. It's free to read online, and I'll be reading it soon.
