### ISSUE TITLE
Commentary

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#12]
Each entry should have a short commentary on why it's worth reading (consuming). Should be added by someone that has already consumed it.

If you've read/consumed any of the items. Please consider helping out and add some commentary.

Example:

> A heavyweight read, so not the best starter novel, but good if you're into futuristic philosophy.

**Comment by hiddentao** [comment]
Just looking through the list we have subsections such as "Dystopia", "Hard Science Fiction" and "Cyberpunk". I think it's worth adding a short sentence or two about what these mean, underneath the respective headings.

**Comment by RichardLitt** [comment]
I like it.

**Comment by sindresorhus** [comment]
@hiddentao Yes, that would be very helpful :)

**Comment by RichardLitt** [comment]
Should we source whoever contributed the commentary? Seems weird to use the first person, without that.

**Comment by sindresorhus** [comment]
Yeah, I was thinking the same:

> Good book - @sindresorhus

**Comment by RichardLitt** [comment]
Added my name to all of the ones I added.

**Comment by aleksandar-todorovic** [comment]
Do you think that we need commentaries in the movie category too? I mean GoodReads pretty much explains the movie, and I think that most of the comment would end up being like this:

> Hey, this movie is amazing! I highly recommend it! - @aleksandar-todorovic

**Comment by RichardLitt** [comment]
Yes. Comments aren't meant to explain the movie, but rather to explain why it should be on this list. If your comment is 'This is amazing', it probably needs some work. Rather, it should be about why it is amazing. Make sense?

**Comment by aleksandar-todorovic** [comment]
I added some commentaries in #91. Please review them. I'm not sure are they too subjective for this list or not.

**Comment by aleksandar-todorovic** [comment]
Right now, adding the commentary is stated as optional in our `contributing.md` file.

We could change that to obligatory and state that the Pull Requests without the commentary would not be accepted until one is added.

That would make our job much easier. It's silly even to consider reading _every_ suggested novel just so we could add our own comment.

**Comment by sindresorhus** [comment]
:+1:

**Comment by RichardLitt** [comment]
Sounds good to me. I think comments are necessary, to be honest; we've been having much more discussion recently.

**Comment by aleksandar-todorovic** [comment]
OK, in that case, I changed the `contributing.md` file. Comments are now obligatory.

**Comment by RichardLitt** [comment]
:+1:

**Comment by RichardLitt** [comment]
I don't think we need this issue to be permanently open. I added an example of how to add just a commentary to the Contirbute. 

And @sindresorhus closed this while I was writing this. Thanks!
