### ISSUE TITLE
Linking author's names to their Wikipedia or Goodreads profile

### ISSUE THREAD

**Issue by aleksandar-todorovic** [sindresorhus/awesome-scifi#121]
### Current situation

The name of the author is displayed with the italic font.

### Proposition to make it better

Link the name of the author to their Goodreads page so the readers could see all of the books published by the author and drop the italic-ing of the font.

### Example

Instead of this:

> [A Fire Upon the Deep](https://www.goodreads.com/book/show/77711.A_Fire_Upon_the_Deep) (1992) _by Vernor Vinge_ [4.1]

Maybe we could make the entries look like this?

> [A Fire Upon the Deep](https://www.goodreads.com/book/show/77711.A_Fire_Upon_the_Deep) (1992) by [Vernor Vinge](https://www.goodreads.com/author/show/44037.Vernor_Vinge) [4.1]

I'm also thinking about linking to the website of the author if he has one. Your opinions?

**Comment by elssar** [comment]
:+1:

**Comment by RichardLitt** [comment]
Sounds good to me! I also agree that we should get rid of Goodreads links if there is a better source to link to. perhaps there should be a way to display both links, however?

**Comment by aleksandar-todorovic** [comment]
OK then, we might do something like this.

We could have three sources: **author's website**, **Wikipedia entry** (if he has one of course) and their **Goodreads page**.

We could prioritize them and say that one of those sources should be the primary one (my suggestion is the website), the second one (Wikipedia entry) and the third one could be their Goodreads page if we can't find any other source with higher priority.

**Or** we could do something like this:

> [A Fire Upon the Deep](https://www.goodreads.com/book/show/77711.A_Fire_Upon_the_Deep) (1992) [4.1] by **Vernor Vinge** ([Wikipedia](https://en.wikipedia.org/wiki/Vernor_Vinge) | [Goodreads](https://www.goodreads.com/author/show/44037.Vernor_Vinge))

If there's a website (which I couldn't find in this particular case for Vernor), then we would include the website as well. Again, we would have to prioritize the sources so there's an easy guide to follow for new entires.

**Comment by mihailim** [comment]
I like this option best:

> [A Fire Upon the Deep](https://www.goodreads.com/book/show/77711.A_Fire_Upon_the_Deep) (1992) [4.1] by **Vernor Vinge** ([Wikipedia](https://en.wikipedia.org/wiki/Vernor_Vinge) | [Goodreads](https://www.goodreads.com/author/show/44037.Vernor_Vinge))

provided that we make it clear that it's not mandatory to include more than one source.

Reason: The author websites, while in theory authoritative, are sometimes run by the publisher marketing departments and drop old content to focus on new releases--thus making them less useful than Goodreads or Wikipedia. Additionally, GR and WP have the advantage of being consistently laid out interfaces where people can easily navigate to different works by the same author or within the same genre...

**Comment by sindresorhus** [comment]
Having both Goodreads and Wikipedia feels like bloat. I think we should only go with Wikipedia. Definitely don't want to link to the author website as they're usually just marketing sites and even if not, the info you want is not easily readable.

**Comment by elssar** [comment]
I feel that one entry should suffice. I personally prefer wikipedia. But sometimes wikipedia entries are quiet sparse. If that happens with one of the authors, maybe we should link to goodreads instead.

**Comment by RichardLitt** [comment]
Sounds good to me. If wikipedia, link. If not, Goodreads. If not, no link. Add it to the contrib doc?

**Comment by sindresorhus** [comment]
:+1:

**Comment by mihailim** [comment]
Wrote up the proposed changes and their application onto the list. Separate pull requests since we might still want to rephrase the guidelines (in case my wording was too fluffy), but the list changes as such would remain the same.

**Comment by mihailim** [comment]
Ah, damn and blast, just noticed I didn't drop the italics.

On the other hand, it doesn't look half bad the way it is, and it does serve as a visual clue offsetting the name from the title. This could be useful since they're both links now and they're close together.

**Comment by RichardLitt** [comment]
I like the italics. I think this works fine.

**Comment by mihailim** [comment]
All merged, thanks.
