### ISSUE TITLE
Add Dune TV Series

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/awesome-scifi#125]
Children of Dune was pretty amazing, as was the Dune miniseries made for the sci-fi channel.

**Comment by mihailim** [comment]
We could... Out of all (big *or* small screen) *Dune* adaptations, I felt this one has come closest to Herbert's vision. They didn't go too crazy on the CGI either, in that it didn't distract from the story. The acting was a bit meh, but that's usually a question of budget (wasn't HBO... :wink:). Given the dearth of good SF on TV, I would consider it awesome by comparison.
