### ISSUE TITLE
Add Orthogonal

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/awesome-scifi#127]
@mihailim have you read this? Can you add it?

**Comment by mihailim** [comment]
I haven't read it, sorry :) While I like Egan's work very much (hard SF fan here, and he's the *epitome* of a hard SF writer), I couldn't find the time to do read it yet. It's not an easy read, you (quite literally, sometimes) have to work at it; having a good understanding of physics, geometry and calculus not only helps immensely, it's close to being a prerequisite.
