### ISSUE TITLE
Round the rating

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#13]
IMHO `[4.32]` is way too specific and not very useful. I think we should round it `[4.3]`. Thoughts?

**Comment by ocombe** [comment]
Sure, the rating is subject to change anyway (people keep voting), and it's just an indication

**Comment by cassidoo** [comment]
I agree.  Would adding a `~` be good, here?

**Comment by sindresorhus** [comment]
@cassidoo How about just mention it at the top so we don't have to have `~` in every box?

> The [number] at the end is the rounded version of the rating on Goodreads.

**Comment by cassidoo** [comment]
I like that, much cleaner.
