### ISSUE TITLE
Rename "Short Stories" to "Short Story Collections"?

### ISSUE THREAD

**Issue by mihailim** [sindresorhus/awesome-scifi#130]
I think we should rename the "Short Stories" section to "Short Story Collections"--all existing entries there are collections as opposed to individual short stories, and so far all suggestions and discussions I've seen here talk about SSCs as well.

**Comment by RichardLitt** [comment]
Good idea. Thanks!

**Comment by aleksandar-todorovic** [comment]
:+1:
