### ISSUE TITLE
Add `Accelerando`

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/awesome-scifi#142]
This was suggested in #88. Anyone read it? 

https://en.wikipedia.org/wiki/Accelerando

**Comment by RichardLitt** [comment]
Asked on Twitter: https://twitter.com/richlitt/status/634805583976235008

**Comment by erbridge** [comment]
Accelerando is an excellent exploration of Posthumanism. It's my go to recommendation for people wanting to read about that stuff.

**Comment by RichardLitt** [comment]
@erbridge Awesome! Want to add a PR with that accolade on it?

**Comment by erbridge** [comment]
Sure, but not sure where to file it...

**Comment by erbridge** [comment]
I just put it in the general Science Fiction section.

**Comment by RichardLitt** [comment]
Works! Thanks!
