### ISSUE TITLE
Add 'Suggested Books' section

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/awesome-scifi#145]
We have a host of issues looking for people to comment on books. Maybe it would be good to have a section saying: "We've heard these books are awesome, but no one has thought they were awesome enough to commit. Would you like to?" This might up engagement. 

Staying with issues also a good option.

**Comment by sindresorhus** [comment]
Sure, sounds like a good idea. Put it on the top.

**Comment by RichardLitt** [comment]
PRed.
