### ISSUE TITLE
[suggestion] The Door Into Summer by Heinlein

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#15]
https://twitter.com/mojombo/status/558364606809124866
http://www.goodreads.com/book/show/348.The_Door_Into_Summer

Thoughts?

**Comment by ashumeow** [comment]
:+1:

**Comment by cassidoo** [comment]
:+1:

**Comment by hiddentao** [comment]
+1

**Comment by sindresorhus** [comment]
@ocombe Thoughts on which category to put this in?

**Comment by ocombe** [comment]
The first one, "Science Fiction" :)
