### ISSUE TITLE
Adding Mr. Robot to the TV Series section?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [sindresorhus/awesome-scifi#151]
Okay, first things first, Mr. Robot is a TV show that started broadcasting this summer and blew everyone's mind. Its first season finale is tomorrow and it got really popular on the internet. The show is as awesome as it can get (its current [IMDB rating](http://www.imdb.com/title/tt4158110/) is 9.1).

But is it really science fiction or not? I'm not sure.

On one hand, the show was written with a goal of being as realistic as possible. On the other hand, it has one imaginary company that rules like every industry from technology to food, an illuminati-like scenario where the main character is trying to fight against the richest ("top 1% out of the top 1%" as he calls them) using his hacking skills which he's using sort of like it's his superpower (and unlike every other hacking-related show and movie I've seen, this time, hacking seems as plausible as it can get in a TV show).

I _think_ that anyone who's watching it will say that it has some elements of mild science fiction and therefore deserves a spot on this list. I also think that nobody is going to object if we call it awesome. I just don't know if it has enough Sci-Fi elements to be a part of this list so I'm submitting this as an issue.

I highly recommend it. It got me hooked even more than Game of Thrones did when I first discovered it. It's a bit too early too call it my favourite TV show, but it already deserved a place in my top three list for sure.

**Comment by RichardLitt** [comment]
Well, my sister likes it, so, that's a :+1:

**Comment by sindresorhus** [comment]
I like it too, but also not sure whether it's scifi enough.

**Comment by RichardLitt** [comment]
So, I'm not sure that this is science fiction. It could just be... fiction. I'm closing this. Reopen if strong objections.
