### ISSUE TITLE
Emoji not working

### ISSUE THREAD

**Issue by Semigradsky** [sindresorhus/awesome-scifi#16]
Emoji not working :cry: 
![image](https://cloud.githubusercontent.com/assets/1198848/5903920/9ed3e734-a595-11e4-92b3-8cdb8b947da3.png)

**Comment by ocombe** [comment]
yes, github disabled the emoji on long md files because it was affecting the performance, they are investigating on it...

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-scifi/issues/1#issuecomment-71055574
