### ISSUE TITLE
Add `Dad's Nuke`?

### ISSUE THREAD

**Issue by cassidoo** [sindresorhus/awesome-scifi#169]
Suggested by a coworker.  Author also wrote Half-Life and Portal.

http://www.goodreads.com/book/show/730945.Dad_s_Nuke

http://www.amazon.com/Dads-Nuke-Marc-Laidlaw/dp/1555471471

**Comment by RichardLitt** [comment]
Looks cool to me! Could you get your coworker to add a comment about why? That way we can merge it in, referencing them as the comment source (or you and their rec).

**Comment by jackflips** [comment]
https://github.com/sindresorhus/awesome-scifi/pull/170

:)

**Comment by RichardLitt** [comment]
All good! Thanks @cassidoo and @jackflips!
