### ISSUE TITLE
:star: and :fire: replaced with actual images

### ISSUE THREAD

**Issue by cassidoo** [sindresorhus/awesome-scifi#17]
What if we replaced all of the `:star:` and `:fire:` parts with:

`<img src="http://i.imgur.com/yJaoHfh.png" width="30px">` <img src="http://i.imgur.com/yJaoHfh.png" width="30px">
and
`<img src="http://i.imgur.com/iA6WScw.png" width="30px"> ` <img src="http://i.imgur.com/iA6WScw.png" width="30px">

**Comment by sindresorhus** [comment]
Sure. Let's go with that for now.

**Comment by ashumeow** [comment]
:+1:

**Comment by hiddentao** [comment]
How do we know those images will always be available?

+1

**Comment by ocombe** [comment]
If it doesn't we'll changed the links. Also we will probably put emoticons back once they work again.
