### ISSUE TITLE
Either rename the repo to awesome-fiction or delete things like 1984/Clockwork Orange/Brazil

### ISSUE THREAD

**Issue by vtdmhd** [sindresorhus/awesome-scifi#186]
After all, sci-fi stands for "scientific fiction"

**Comment by aleksandar-todorovic** [comment]
There's already [`awesome-fantasy`](https://github.com/RichardLitt/awesome-fantasy) that might be like what you had in mind, but it didn't gain as much popularity as this one did.

**Comment by augustopedro** [comment]
But 1984/Clockwork Orange/Brazil are science-fiction :hushed:

**Comment by RichardLitt** [comment]
Wikipedia: 

> Science fiction is a genre of speculative fiction dealing with imaginative concepts such as futuristic settings, futuristic science and technology, space travel, time travel, faster than light travel, parallel universes and extraterrestrial life. Science fiction often explores the potential consequences of scientific and other innovations, and has been called a "literature of ideas."[1] It usually eschews the supernatural, and unlike the related genre of fantasy, historically science fiction stories were intended to have at least a faint grounding in science-based fact or theory at the time the story was created, but this connection has become tenuous or non-existent in much of science fiction.

I think I'm OK with 1984/ Clockwork Orange being on here, but I don't know, because I haven't read them. Brazil is science fiction, I feel - it deals with a world in the far future. I think nitpicking what is scifi and what isn't would be worse for the list than including really awesome fiction that is only vaguely scifi.

**Comment by augustopedro** [comment]
Yeah, indeed. I believe that sci-fi is more a background than a genre. Back To The Future, for example, is an adventure movie, with a sci-fi background. Terminator is an action movie, with a sci-fi background. The Thing from Another World is a horror movie, with a sci-fi background.

**Comment by RichardLitt** [comment]
[Ursula Le Guin](http://www.theparisreview.org/interviews/6253/the-art-of-fiction-no-221-ursula-k-le-guin):

> I don’t think science fiction is a very good name for it, but it’s the name that we’ve got. It is different from other kinds of writing, I suppose, so it deserves a name of its own. But where I can get prickly and combative is if I’m just called a sci-fi writer. I’m not. I’m a novelist and poet. Don’t shove me into your damn pigeonhole, where I don’t fit, because I’m all over. My tentacles are coming out of the pigeonhole in all directions.

I am closing this issue.
