### ISSUE TITLE
Vorkosigan Saga by Lois McMaster Bujold 

### ISSUE THREAD

**Issue by uraimo** [sindresorhus/awesome-scifi#205]
I've actually read only "Shard of Honour" and "The Vor Game" so i can't comment on the series as a whole but it's a classic, well written and with interesting characters.

https://www.goodreads.com/series/98250-vorkosigan-saga-publication

**Comment by RichardLitt** [comment]
Cool! Anyone else read it?

**Comment by RichardLitt** [comment]
Well that's a statement. @will-hart Want to add it to the list?

**Comment by will-hart** [comment]
I can have a go... might take me a few days to pull together the PR

**Comment by RichardLitt** [comment]
Bump.
