### ISSUE TITLE
Links section

### ISSUE THREAD

**Issue by davidmerrique** [sindresorhus/awesome-scifi#21]
Thoughts on a section of links to other lists?
This just popped up on Hacker News:

https://news.ycombinator.com/item?id=9056319

**Comment by sindresorhus** [comment]
:+1:

**Comment by davidmerrique** [comment]
:+1:

**Comment by sindresorhus** [comment]
http://www.reddit.com/r/AskReddit/comments/k70dh/whats_the_best_scifi_novel_you_have_ever_read/
