### ISSUE TITLE
Consider adding Open Your Eyes

### ISSUE THREAD

**Issue by uraimo** [sindresorhus/awesome-scifi#210]
Vanilla Sky is actually based on Open Your Eyes (Abre Los Ojos http://www.imdb.com/title/tt0125659/?ref_=fn_al_tt_1), that is by many (me included) considered to be a better movie even if it's a low cost production. Following what was done with Solaris, this could be added to the list too.

Just for reference, the story is essentially the same and the main difference is a objectively better acting.

**Comment by RichardLitt** [comment]
Whoa! I did not know that! 

Solaris is also awesome. Add your entry?

**Comment by uraimo** [comment]
Ok, will open a PR!

Also, i was thinking of adding Dark City but i'm not sure it fits here, what do you think?

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/awesome-scifi/commit/73fd3e7fcc15b0d1691fa537fe94690c6813d300.

**Comment by parro-it** [comment]
I saw both year ago, "Abre Los Ojos" is really better than the most known Vanilla Sky
