### ISSUE TITLE
March: Diamond Age by Neal Stephenson

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/awesome-scifi#223]
What should we read this month? One comment per user, and let's vote using 👍. I'll abstain because my book was chosen last month (https://github.com/sindresorhus/awesome-scifi/issues/222). Voting will close on March 10th at Midnight EST. 

cc @ArcAster @Alex-Keyes @leobalter @fritzvd @AgFlow

**Comment by Alex-Keyes** [comment]
Hey all,

did you guys see my glitter chats?  I think this month we should have a specific time we can all get on glitter and discuss the book.  Generally it seems like we didn't get off to the best start with pattern recognition. 

I'd like to nominate [frend by jonathan miller](https://www.amazon.com/frend-Jonathan-R-Miller-ebook/dp/B00OACA0KE/ref=sr_1_1?ie=UTF8&qid=1488985722&sr=8-1&keywords=frend).  I've been thinking about what it would be like to become a cyborg and have my body replaced by metal limbs so this kind of book seems in my wheelhouse.  Thoughts everyone?

**Comment by RichardLitt** [comment]
> did you guys see my glitter chats? I think this month we should have a specific time we can all get on glitter and discuss the book. 

Yep! I responded a bit ago. Might be hard - looks like we're in different time zones. 

> Generally it seems like we didn't get off to the best start with pattern recognition.

Agreed! Sad times. Heard it was good, I guess I should have listened closer. 

Friend seems cool. One vote from me. (I think voting multiple times should be fine).

**Comment by RichardLitt** [comment]
> I don't want to keep the conversation going there without reason though, just a few thoughts I had on the book.

Is there more you want to discuss? 

> How can we establish a consensus if we all can vote as much as we like?

Good point. Alright, changing my mind; one vote per person. We can still check that easily, there aren't too many of us. 

We can aim for tomorrow night at 8pm EST, as a tentative time, if you want to discuss more?

**Comment by Alex-Keyes** [comment]
> Is there more you want to discuss?
 No not really, I just wanted to bring up that last thought

>  We can aim for tomorrow night at 8pm EST, as a tentative time, if you want to discuss more?

Yeah okay cool I'll be there!  even if we don't focus on the book, I'd like to get to know everyone better.

**Comment by ferhatelmas** [comment]
My nominee is [The Diamond Age](https://en.wikipedia.org/wiki/The_Diamond_Age). I remember [Peter Norvig](http://norvig.com/) was recommending it as the best science fiction book. A quick search brought this, [best science fiction by experts](http://uk.businessinsider.com/best-robots-science-fiction-ai-experts-say-2015-11).

@RichardLitt Agflow is the company I'm working right now, please use my username next time, thanks!

**Comment by Alex-Keyes** [comment]
@RichardLitt you voting twice or you just liking ferhatmels comment?  Why don't we use a different emojis for votes. 

@ferhatelmas Thanks for the list definitely really cool.  You get my vote. 

When are we gonna decide when to start reading guys?

**Comment by ferhatelmas** [comment]
FYI, I was able to start pattern matching in the beginning of March so I'm still reading pattern matching but should be done this weekend.

**Comment by RichardLitt** [comment]
Ah, you're right! Sorry, voting for Diamond Age. Heard it was really good, and I've been meaning to read it. 

Decide end of day today?

**Comment by Alex-Keyes** [comment]
@RichardLitt Yeah that sounds good.  Also, why don't we use the hearts as our vote?  Starting to get a little confused lol

**Comment by RichardLitt** [comment]
Hahaha Yeah. Ok. Hearts for votes. Let it be written. Let it be done.

**Comment by RichardLitt** [comment]
So! Diamond age it is!

**Comment by fritzvd** [comment]
I'm in. Just purchased waiting for it to ship. 

Is it possible to decide on a book before the beginning of the month in stead of having to hurry. I probably won't finish before April. That's also what held me back last month. Knowing I won't make it in two weeks.

**Comment by JIghtuse** [comment]
@RichardLitt uhm, Diamond Age was recommended by Peter Norvig, he is not an author. It is Neal Stephenson.

**Comment by RichardLitt** [comment]
Nothing to see here.

**Comment by RichardLitt** [comment]
> Is it possible to decide on a book before the beginning of the month in stead of having to hurry. I probably won't finish before April. That's also what held me back last month. Knowing I won't make it in two weeks.

I think so. How do you all feel about taking a month and a half for Diamond Age? It's almost 500 pages.

**Comment by ArcAster** [comment]
Taking more time sounds like a good plan.

**Comment by Alex-Keyes** [comment]
hey all how is the reading going?  It's been a while haha.

**Comment by RichardLitt** [comment]
:D I finished it a couple of days ago, and now have dozens of notes to write up. I was hoping to post here at some point soon; talk about a delay. I feel pretty guilty, ya'll. 

I know @fritzvd finished it. \o/

How are you doing, @Alex-Keyes?

**Comment by fritzvd** [comment]
I did finish. We sort of started a conversation on gitter.im

But if everybody read the book, I'm totally done for a breakdown of the book. I just kind of waited for the rest to finish up.

For the next book. I've got a copy of Robert A. Heinlein's The Moon's a Harsh Mistress lying around as well as Ender's Game by Orson Scott Card. So either of those, would be very practical. But if anyone wants something else, I'm up for that as well.

**Comment by Alex-Keyes** [comment]
Unfortunately I didn't finish (work has pervaded almost all aspects of my life) but I'd be glad to listen in on the discussion and move on to the next book.  My greatest concern is keeping this group going.  

The Ender series is one of my favorites so I vote for Ender's game.  It's also a short and easy read so that should prove a nice counterbalance to Diamond Age.

**Comment by RichardLitt** [comment]
Let's go with Ender's Game. Makes it a lot easier, and should be doable by the end of the month. :)

**Comment by RichardLitt** [comment]
I wrote my review up here: https://www.burntfen.com/the-litt-review/the-diamond-age/

Closing this now, as it's a couple of months old. :)
