### ISSUE TITLE
May: Ender's Game by Orson Scott Card

### ISSUE THREAD

**Issue by Alex-Keyes** [sindresorhus/awesome-scifi#225]
Hello All, 

From our vote in [issue #223 ](https://github.com/sindresorhus/awesome-scifi/issues/223), we decided the book of the month is Ender's Game by Orson Scott Card.  This is a nice and easy read (I first read it in 6th grade) so it should be a nice change of a pace from the heavy fiction that we've been reading.  

Looking forward to discussing it!

**Comment by fritzvd** [comment]
This was great. I'm not great at writing reviews. But here's mine:

https://www.goodreads.com/review/show/753407624

**Comment by RichardLitt** [comment]
And mine. Thanks, @fritzvd! https://www.burntfen.com/the-litt-review/enders-game/
