### ISSUE TITLE
July: Borne by Jeff Vandermeer

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/awesome-scifi#226]
Anyone feel like reading anything this July? 

I, for one, enjoy reading the books, but I have been traveling and AFK too much to write about them. 👎 Ah well. 

Suggest some things. Voting will close on Friday. :)

**Comment by davidmerrique** [comment]
I'm thinking of starting [Borne by Jeff VanderMeer](https://www.goodreads.com/book/show/28225843-borne)

**Comment by thejessleigh** [comment]
New to this project, but I love this reading group idea. I second [Borne](https://www.goodreads.com/book/show/28225843-borne).

**Comment by ferhatelmas** [comment]
If we have only one option, then it's too easy :smile_cat: 

What about [Station Eleven by Emily St. John Mandel](https://www.goodreads.com/book/show/20170404-station-eleven) ?

**Comment by RichardLitt** [comment]
I think we're going with Borne. @ferhatelmas maybe next month!

Alright, all, grab the book and let's go. As always, discussion is welcome on Gitter, and if you're really keen, email someone who says they're reading it here and talk with them.

**Comment by fritzvd** [comment]
Whoops missed this. I'll pick up the group in August again. I'm reading [Margaret Atwood's - The Blind Assasin](https://www.goodreads.com/review/show/753407624) at the moment

**Comment by RichardLitt** [comment]
Mine is in the mail. Should be finished by August. :) How is everyone else doing?

**Comment by thejessleigh** [comment]
This month is really getting away from me and I haven't had a chance to start yet.

**Comment by davidmerrique** [comment]
Going great! Nearing the end now.

**Comment by Alex-Keyes** [comment]
phew I totally missed this.  Sorry guys! Looking forward to hearing your thoughts about it though.

**Comment by RichardLitt** [comment]
@davidmerrique @thejessleigh Jump on the Gitter! Or PR this thread with your review. :)
