### ISSUE TITLE
Stargate 9000+ hours

### ISSUE THREAD

**Issue by matejferenc** [sindresorhus/awesome-scifi#234]
Probably should say "minutes"

**Comment by RichardLitt** [comment]
I think this is a reference to [Over 9000!](http://knowyourmeme.com/memes/its-over-9000). It's hyperbole. @uraimo doubtless didn't actually mean 9000 hours.

**Comment by uraimo** [comment]
Thank you Richard for believing in my proficiency in memes ;D

But actually @matejferenc is right, while I really meant to do a 9000+ joke, there are 214 episodes of average length of 44 minutes, for a total of 9416 minutes. So, I really meant minutes.

**Comment by RichardLitt** [comment]
:D Fixed. Thanks @matejferenc and @uraimo!
