### ISSUE TITLE
Link Vanilla sky in the section Open Your Eyes is wrong

### ISSUE THREAD

**Issue by damaru2** [sindresorhus/awesome-scifi#244]
In the section [Open Your Eyes](https://github.com/sindresorhus/awesome-scifi#open-your-eyes-1997-78) Vanilla Sky has a wrong link. The right one should be https://github.com/sindresorhus/awesome-scifi#vanilla-sky-2001-69

Thanks for the list. It seems pretty good. 
Here are some suggestions of scifi movies I'd include in the awesome list:

+ Mr. Nobody
+ I, Robot
+ Cloud Atlas
+ eXistenZ
+ The hitchhiker's guide to the galaxy
+ The time machine (2002) (I haven't seen the other one)

**Comment by RichardLitt** [comment]
Thanks, David! These are excellent suggestions. I'm surprised Cloud Atlas isn't in here, it was a wonderful film. 

Would you like to make a PR with this information, and your small reviews?
