### ISSUE TITLE
Add Black Science to the Comics Section

### ISSUE THREAD

**Issue by EricPonvelle** [sindresorhus/awesome-scifi#259]
I highly recommend adding the Black Science series to the Comic books section. The series is basically Rick & Morty, if Rick were more inept and had morals. They do a ton of dimension hopping. Here's a series overview:

> Grant McKay, former member of The Anarchistic Order of Scientists, has finally done the impossible: He has deciphered Black Science and punched through the barriers of reality. But what lies beyond the veil is not epiphany, but chaos. Now Grant and his team are lost, living ghosts shipwrecked on an infinite ocean of alien worlds, barreling through the long-forgotten, ancient, and unimaginable dark realms. The only way is forward. The only question is how far are they willing to go, and how much can they endure, to get home again? Join writer RICK REMENDER and the superstar art team of MATTEO SCALERA & DEAN WHITE for this face-melting science fiction epic spanning the lifetimes of a cast of dimensional castaways lead by the man who caused it all.

Comixology Link - https://www.comixology.com/Black-Science/comics-series/11970?ref=c2VhcmNoL2RldGFpbC9kZXNrdG9wL2xpc3Qvc2VyaWVzU2VhcmNoRGV0YWlsTGlzdA

**Comment by RichardLitt** [comment]
Cool! Want to make a PR for this?

**Comment by EricPonvelle** [comment]
Done - https://github.com/sindresorhus/awesome-scifi/pull/262#issue-221581217
