### ISSUE TITLE
The Link to Book 5 of Magic 2.0 is incorrect

### ISSUE THREAD

**Issue by EricPonvelle** [sindresorhus/awesome-scifi#260]
Currently, the link for "Out of Spite, Out of Mind" links to this - https://www.goodreads.com/book/show/36566205-fight-and-flight. This is a duplicate of the previous book link.

It should link here - https://www.goodreads.com/book/show/39751936-out-of-spite-out-of-mind

![image](https://user-images.githubusercontent.com/16167833/46478079-2dbcea00-c7ba-11e8-8ad0-bd3e906ebed4.png)

**Comment by RichardLitt** [comment]
Thanks for pointing this out! If you'd like to make a PR fixing it, I'd be happy to review it.

**Comment by EricPonvelle** [comment]
Sure thing! Are there permissions that I am lacking I got this error when I tried to commit

```
C:\awesome-scifi>git push -u origin HEAD
remote: Permission to sindresorhus/awesome-scifi.git denied to EricPonvelle.
fatal: unable to access 'https://github.com/sindresorhus/awesome-scifi.git/': The requested URL returned error: 403
```

**Comment by EricPonvelle** [comment]
It was way easier to just edit in the browser in the end. Still having issues with local git. Here's the PR!

https://github.com/sindresorhus/awesome-scifi/pull/261#issue-221576476

**Comment by RichardLitt** [comment]
:) Thanks.
