### ISSUE TITLE
ExForce and Omega Force Series

### ISSUE THREAD

**Issue by grr** [sindresorhus/awesome-scifi#309]
These two highly-rated series have the same style of humor as the Bobiverse series:
  * Omega Force by Joshua Dalzelle: https://www.goodreads.com/series/113707-omega-force
  * Expeditionary Force by Craig Alanson: https://www.goodreads.com/series/185650-expeditionary-force

**Comment by RichardLitt** [comment]
PRs accepted.

**Comment by Potherca** [comment]
Usually I'm hesitant to start a series that has so many books added so quickly, so I took a look at the ratings (from GoodReads):

| Book   | Bobiverse  | Expeditionary Force  | Omega Force |
| -----: | ---------: | -------------------: | ----------: |
|     1. |       4.28 |                 4.26 |        4.07 |
|     2. |       4.37 |                 4.23 |        4.23 |
|     3. |       4.41 |                 4.25 |        4.29 |
|     4. |       4.31 |                 4.33 |        4.32 |
|     5. |            |                 4.37 |        4.36 |
|     6. |            |                 4.23 |        4.40 |
|     7. |            |                 4.37 |        4.41 |
|     8. |            |                 4.41 |        4.49 |
|     9. |            |                 4.37 |        4.58 |
|    10. |            |                 4.53 |        4.52 |
|    11. |            |                 4.47 |        4.57 |
|    12. |            |                 4.52 |        4.58 |
|    13. |            |                 4.58 |        4.65 |
|  <hr>  | <hr>  | <hr> | <hr> |
| Mean   |       4.34 |                 4.36 |        4.42 |
| Median |       4.34 |                 4.37 |        4.41 |



Both Expeditionary Force and Omega Force seems to starts out quite weak.
It looks like they pick up speed halfway through the series.

Although that might be skewed by the fact that for later books, only hard-core readers will still be following...

@grr Have you read either of these series? Are they really any good? 

And, of course, the obligatory diagram:

[![](https://docs.google.com/spreadsheets/d/e/2PACX-1vTcUFCeAMpT6qozIHk4VBFVcE68P_R__7u3YVmt1ahRSD0CFLx5TU6Bp4OoDqo5s6bLqdY4O7X2Nis6/pubchart?oid=651125799&format=image)](https://docs.google.com/spreadsheets/d/1t-G_aKXvAxWtolyaqvzYabApNlbnMsXvw7yIZCyTquY/edit?usp=sharing)

**Comment by Potherca** [comment]
> both series are exclusive to kindle, hence the lower ratings count 

Ah! That might also explain the higher ratings for the audiobooks (on Amazon) compared to the written versions (on Goodreads).

I've added them on my "To Read" list. I'll report back in a year or two when I finally get to them :joy:

**Comment by Potherca** [comment]
I managed to read a good chunk of Expeditionary Force but I had to stop after book 4 as it was just too poorly written to go on.

This is just my opinion, but for me Expeditionary Force falls quite short of the "Awesome" mark.

**Comment by RichardLitt** [comment]
Thanks, all. I think let's just close this. If someone wants to open a PR, go for it!
