### ISSUE TITLE
Use collapsible/spoiler section for details

### ISSUE THREAD

**Issue by grr** [sindresorhus/awesome-scifi#310]
It would be easier to scan through the list if the details were hidden until clicked. Can easily be done:
https://stackoverflow.com/questions/32814161/how-to-make-spoiler-text-in-github-wiki-pages

**Comment by nahkampf** [comment]
@RichardLitt if you're fine with the solution below, I could take it upon myself to edit the document to put all the descriptions into "spoiler" tags?

<details>
  <summary>Description</summary>
    > Text from goodreads or whatever here. 
</details>

**Comment by RichardLitt** [comment]
Sounds fine to me. @sindresorhus?

**Comment by sindresorhus** [comment]
👍

**Comment by nahkampf** [comment]
https://github.com/sindresorhus/awesome-scifi/pull/318
