### ISSUE TITLE
Screamers (1995)

### ISSUE THREAD

**Issue by johan-stenqvist** [sindresorhus/awesome-scifi#329]
Would Screamers (https://www.imdb.com/title/tt0114367/) be something to be added to this list? I guess we can always argue about "awesome"... :)

**Comment by RichardLitt** [comment]
If you think it's awesome, sure.

**Comment by johan-stenqvist** [comment]
I absolutely think its awesome!

**Comment by RichardLitt** [comment]
Then add it!
