### ISSUE TITLE
Video Games Category

### ISSUE THREAD

**Issue by gilStettler** [sindresorhus/awesome-scifi#331]
Hi there!

Thank you so much for maintaining this list. It’s a great resource for someone like me, who is fairly new to the Sci-Fi genre.

While browsing the list, I noticed there isn’t a category for video games. I understand the list may have originally been focused on novels, but since there are already categories for movies and TV shows, I thought this addition could be appreciated.
I believe video games are a fantastic medium for experiencing the Sci-Fi genre in a very interactive way. There are many great examples of Sci-Fi games, such as Astroneer, Cyberpunk 2077, and Warhammer 40k: Rogue Trader—all of which I’ve played and enjoyed. These titles, among others, might appeal to others as well.

If you like the idea, please let me know—I’d be happy to contribute, for instance, by submitting a PR.

Greetings,
Gil

**Comment by RichardLitt** [comment]
Thanks. I'm not interested in that section, at the moment. Feel free to make your own list though. :)
