### ISSUE TITLE
Add Star Trek films

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/awesome-scifi#45]
We need to add some. Which ones? All of them?

**Comment by sindresorhus** [comment]
Maybe add the best ones, and link to the rest on IMDB (or some other site).

**Comment by elssar** [comment]
I think we should have a main entry for each series, with its own link, rating, commentary and synopsis. Any individual entry from the series can be added as a sub item of the series.

#### Star Trek [7.7]

[commentary]

> [synopsis]

###### Star Trek II:: The Wrath of Khan [7.7]

[commentary]

> [synopsis]

Not sure how to handle edge cases like reboots. Maybe a separate entry for them. So the original Star Trek movies would have their own entry, and likewise for The Next Generation, and the recent reboots. Or maybe everything under one main entry.

**Comment by RichardLitt** [comment]
I think having a header works, but I don't think it should have a rating, and the link should be able to go somewhere besides IMDB, like Wikipedia. Star Trek, in particular, has had too many reboots to make any top rating just not meaningful.

**Comment by sindresorhus** [comment]
:+1:

**Comment by RichardLitt** [comment]
Actually, I'm not sure I like the films being smaller than the other films, just because they're in a series. Maybe we could make a ##Movies and a ## Movie Series? 

![screenshot 2015-05-22 10 38 33](https://cloud.githubusercontent.com/assets/910753/7763679/d91038c4-006e-11e5-9e15-176eac83e9f1.png)

**Comment by sindresorhus** [comment]
Sure, that way they also won't take up so much space when reading through the movie list.

**Comment by aleksandar-todorovic** [comment]
Since the movie series had been added to the list, maybe this issue needs to be closed now?

**Comment by RichardLitt** [comment]
Works for me. 



—
