### ISSUE TITLE
Replace images with Emoji

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/awesome-scifi#60]
On GitHub, you can just use :fire: and :star: instead of the images and it renders. I think this makes a lot more sense than the image thing we have at the moment, which is too big for the line and requires strange copy pasting. 

Shall I switch them?

**Comment by sindresorhus** [comment]
They're images for a reason... https://github.com/sindresorhus/awesome-scifi/issues/16 Bug GitHub about it ;)

**Comment by RichardLitt** [comment]
Ah, jerks. Alright then.
