### ISSUE TITLE
A year of publication?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [sindresorhus/awesome-scifi#79]
In some (if not all) categories, the year of publication could have a huge impact on the visitor in his decision to read / watch the entry or not.

I think that this list needs to have a year of the (first) publication next to the name of the entry. I'll be more than happy to contribute to the list by adding this info next to the every entry in the list.

My suggestion on the format: 

    #### [TITLE](LINK) (YEAR) *by AUTHOR* [RATING]

**Comment by elssar** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by RichardLitt** [comment]
:+1:
