### ISSUE TITLE
Organizing movies in categories

### ISSUE THREAD

**Issue by aleksandar-todorovic** [sindresorhus/awesome-scifi#83]
Since we already have a lot of movies added to this list, maybe we should start organizing them in different categories like we already categorized books?

**Comment by RichardLitt** [comment]
Agreed!

**Comment by aleksandar-todorovic** [comment]
Anyone got some input on which categories to create? If so, I'm more than happy to resolve this issue.

**Comment by icyflame** [comment]
@aleksandar-todorovic 

These are the preliminary categories that I propose : -

1. Post apocalyptic
2. based on Robots
3. based in the far-future (about 50-100 years from the year the movie itself was released) (I need suggesstions on this one, some post-apocalyptic movies may come here, but movies like `Her` belong here.)
4. Movies adapted from Books (Ender's Game, which is currently not on the list)

**Comment by elssar** [comment]
If we are adding categories for movies, then maybe it's worth considering having books and movies as sub-categories of a category.

**Comment by aleksandar-todorovic** [comment]
@icyflame I was thinking more about grouping them by their subject. So something like this:

* **AI / Robots** - Anything related to Artificial Intelligence would go here. So Chappie, Her and everything similar.
* **Apocalyptic** - which will also include post-apocalyptic movies as well.
* **Related to aliens** - So District 9, Age of Tomorrow and similar would go here.
* **Hacking-related** - like Hackers, 2001: A Space Odyssey, The Matrix...

Of course, the problem would be that some movies might seem fit for more than one category. In that case, I'm not sure should we add them to both categories or just to the most dominant one.

@elssar I'm not sure can we apply the same categories to movies as we did with novels. There are far less entries to the movies section than the novels section. Maybe we should group them by their subject for now and use the categories we used for novels when we have enough entries?

**Comment by icyflame** [comment]
I agree with @aleksandar-todorovic . (Probably change **Hacking-related** to **Software sci-fi** ? Especially, considering movies like Source Code and Matrix. )

@elssar We should keep movies separate and categorize them, accordingly, just like books. Merging books and movies would be a bad idea.

**Comment by RichardLitt** [comment]
@simonv3 Did we ever find a way to deal with tags in Markdown?

**Comment by simonv3** [comment]
@RichardLitt Not if you stick to a markdown page. You can parse the data and store it in some other way of course.

**Comment by aleksandar-todorovic** [comment]
Maybe creating a couple of images (like the `awesome` badge) and use them?

**Comment by RichardLitt** [comment]
That would work. We could also use inline code blocks. `apocalyptic`, `fantasy`, `really awesome`.

**Comment by RichardLitt** [comment]
IMDB has movie categories, but they're largely useless: `Drama`, `Romance`, `SciFi`. 

Regarding @icyflame's suggestions, I'm not sure - _Her_ isn't far future, it's relatively close. Also, 'Novels based on Books' doesn't say anything about the type of movie it is. 

_The Terminator_ is, at once, about AI / Robots, the apocalypse, aliens (I think?), and hacking related. So, I'm not sure that those categories would stand up too well on their own. 

Why don't we do this: 

```
#### [Serenity (Firefly)](http://www.imdb.com/title/tt0379786/) (2005) [8.0]

Categories: `space`, `futurist`, `western`. 

> The crew of the ship Serenity tries to evade an assassin sent to recapture one of their number who is telepathic.
```

The category tags could be soft tags, and we could add to them or not as we see fit. The point wouldn't be categorization, but just saying what movies are like a bit better.

**Comment by sindresorhus** [comment]
:+1: Though the categories are tags, so they don't need to be comma separated or dot at the end:

```
#### [Serenity (Firefly)](http://www.imdb.com/title/tt0379786/) (2005) [8.0]

Categories: `space` `futurist` `western`

> The crew of the ship Serenity tries to evade an assassin sent to recapture one of their number who is telepathic.
```
