### ISSUE TITLE
Add `Babylon 5`?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#87]
Suggested on Reddit:
https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crrdsw7

**Comment by RichardLitt** [comment]
Debatable. I really didn't think Babylon 5 was awesome.

**Comment by elektrovert** [comment]
Babylon 5's special effects left a lot to be desired, but the plot was amazing.

**Comment by mihailim** [comment]
The CGI hasn't aged well--but on the other hand the show's strength lies in character development and (on a meta level) the pre-planned structure which is fairly unique for TV series. On the other hand, it's a polarizing show... So my vote is a conditional yes :)
