### ISSUE TITLE
Suggestions from Reddit

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#88]
From this thread: https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/

-

> Ron L Hubbert - Battlefield Earth. o_O
> You might include some Charles Stross in Hard SF. I am not so good in english so maybe someone else should write make that entry. Accelerando is a must there. Also Glasshouse!
> - https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crrcgut

-

> The movie list is also a bit short.
> - https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crrgzyz

-

> What the hell happened at the short story section? So many great short story collections out there, so many short stories that worm into your mind or soul and won't come out, and the only entry is Hamilton's? The book was okay if you like Hamilton, but they are not good short stories.
> - https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crrhgxu

-

> Kind of minimal on the short fiction, there.
> - https://www.reddit.com/r/scifi/comments/380izr/scifi_worth_consuming/crrhefn

**Comment by RichardLitt** [comment]
Short story section certainly needs more.

**Comment by RichardLitt** [comment]
Closing this, because a short list is OK. What's more important is that the list is truly **awesome**. Yeah.
