### ISSUE TITLE
Add some books

### ISSUE THREAD

**Issue by cassidoo** [sindresorhus/awesome-scifi#9]
The Forever War
http://www.goodreads.com/book/show/21611.The_Forever_War

Anathem
http://www.goodreads.com/book/show/2845024-anathem

The Stand
http://www.goodreads.com/book/show/149267.The_Stand

**Comment by vrunoa** [comment]
The end of Eternity by Asimov
http://www.goodreads.com/book/show/509784.The_End_of_Eternity

Read it, pretty good!

**Comment by hiddentao** [comment]
Great! Please raise a PR for these.

**Comment by vrunoa** [comment]
@hiddentao PR created, I add the book I read and also the ones proposed by @cassidoo

**Comment by hiddentao** [comment]
Merged, thanks!
