### ISSUE TITLE
District 9

### ISSUE THREAD

**Issue by elektrovert** [sindresorhus/awesome-scifi#94]
[District 9](http://www.imdb.com/title/tt1136608/) (2009)  Neill Blomkamp, Terri Tatchell [8.0]

> An extraterrestrial race forced to live in slum-like conditions on Earth suddenly finds a kindred spirit in a government agent who is exposed to their biotechnology.

**Comment by aleksandar-todorovic** [comment]
I watched it two or three days ago, but I wasn't really feeling the story. I realize that we might have different opinions, so please write down a short opinion on why you think that this movie is awesome and why do you suggest others to watch it.

After that, I'll create a pull request together with your second addition to the list. I'll link you as the author of those comments of course.

**Comment by sindresorhus** [comment]
:+1: I liked it. Very original.

**Comment by marcoslhc** [comment]
Yep, the idea is pretty cool and original. Although I have some doubts
about the realization. I hope in twenty years someone will make a better
remake :)

*Saludos…*

*Marcos Luis Hernández*
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

1151, Fairlake Tr. #1716.
Weston, FL. 33326

[*website*]: *http://xiryvella.com/ <http://xiryvella.com/>*
[*github*]: *https://github.com/marcoslhc* <https://github.com/marcoslhc>
[*twitter*]: @marcoslhc <http://twitter.com/marcoslhc>
[*mobile*]: +1 954 300 9924
[*info*]: *https://www.google.com/profiles/marcoslhc
<https://www.google.com/profiles/marcoslhc>*

**Comment by RichardLitt** [comment]
I thought it was pretty awesome, even just linguistically. Special effects were great. Interesting given it was South African, too.

**Comment by elssar** [comment]
:+1: I really liked the movie.

**Comment by RichardLitt** [comment]
@elektrovert Want to make a PR? If not, we can do it for you.

**Comment by elektrovert** [comment]
@RichardLitt Yes please! if you could do that, that would be great. I'll do wool.

**Comment by RichardLitt** [comment]
Thanks @elektrovert!
