### ISSUE TITLE
Wool

### ISSUE THREAD

**Issue by elektrovert** [sindresorhus/awesome-scifi#95]
[Wool](https://www.goodreads.com/book/show/13453029-wool-omnibus?from_search=true&search_version=service) (July 2011)  Hugh Howey  [4.3]

>This is the story of mankind clawing for survival, of mankind on the edge. The world outside has grown unkind, the view of it limited, talk of it forbidden. But there are always those who hope, who dream. These are the dangerous people, the residents who infect others with their optimism. Their punishment is simple. They are given the very thing they profess to want: They are allowed outside.

**Comment by aleksandar-todorovic** [comment]
Which subcategory of novels do you feel like this would be a great addition to?

Also, please write down a short personal opinion on why should this novel be on the list of awesome novels.

After you write this down, I'll create a pull request.

**Comment by Racum** [comment]
+1

**Comment by elektrovert** [comment]
@aleksandar-todorovic  It's a dystopian novel, set in the near future. 
I'll get back to you with a personal opinion shortly.

**Comment by aleksandar-todorovic** [comment]
Thanks, looking forward to including it.

**Comment by elektrovert** [comment]
My personal opinion: 
This book is great! Set in the near future, the story follows a number of characters as their lives unfold living in an underground silo. Life underground seems quite grim, people have obviously been down there quite a while, and even though they seem to have quite advanced technology, it's old and decaying. The engineers and mechanics do their best to keep the electricity throughout the 100 levels of the silo, it's a lottery to see who gets to start a family as the population needs to be strictly controlled. 
It's set close enough to the present that you can see how things could end up the way they are in the silo, the political structures, the way the silo is organised, the rivalry between the various levels and departments; but what happened to lead to humanity living this way in the first place? Why are they all down there, and what's wrong with the surface?  
This series of books is well worth a read, I couldn't put it down once I got into the first few chapters. I think this series will be recognised as a sci-fi classic in the coming years.  
Also, the first book is available free on kindle, so it won't cost you anything to check it out - except maybe a kindle.

**Comment by aleksandar-todorovic** [comment]
Thanks! :beers:
